# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='pagos',
            old_name='monto',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pagos',
            name='descuento',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pagos',
            name='pago',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pagos',
            name='precio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pagos',
            name='productos',
            field=models.ForeignKey(blank=True, default=1, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='app.productos'),
            preserve_default=False,
        ),
    ]
