# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180130_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thing',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='productos',
            field=models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='app.Productos'),
        ),
    ]
