# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180130_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='Clasificacion',
            new_name='clasificacion',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cantidad',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='descuento',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pago',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='precio',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='productos',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Productos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='saldo',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='total',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='venta',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tiposventa'),
        ),
    ]
