# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-17 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20171110_1445'),
        ('app', '0032_auto_20171111_1300'),
    ]

    operations = [
    ]
