# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-06 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_pacientes_fecha_ini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha_ini',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medicos',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Medicos'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pacientes'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
