# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20171206_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fecha_ini',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='foto',
            field=models.TextField(blank=True, db_column='foto'),
        ),
    ]
