# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0040_auto_20171212_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300)),
                ('apellido', models.CharField(blank=True, max_length=300)),
                ('dni', models.CharField(blank=True, max_length=300)),
                ('domicilio', models.CharField(max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=300)),
                ('celular', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('referenciado', models.CharField(blank=True, max_length=300)),
                ('foto', models.FileField(upload_to='static')),
                ('ciudad', models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ciudad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
