# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='atencion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Atencion'),
        ),
    ]
