# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_atencion_atencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='atencion',
            new_name='fecha',
        ),
    ]
