# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20180117_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tratamiento',
            old_name='apoyo',
            new_name='Apoyo',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='diagnostico',
            new_name='Diagnostico',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='dolor_fisico',
            new_name='Dolor_Fisico',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='estudio_medico',
            new_name='Estudio_Medico',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='fecha_ini',
            new_name='Fecha_ini',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='firma',
            new_name='Firma',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='frecuencia',
            new_name='Frecuencia',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='malestar_emocional',
            new_name='Malestar_Emocional',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='porcentaje',
            new_name='Porcentaje',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='sesion',
            new_name='Sesion',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='tipo',
            new_name='Tipo',
        ),
        # migrations.AddField(
        #     model_name='tratamiento',
        #     name='medico',
        #     field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Medicos'),
        # ),
        # migrations.AddField(
        #     model_name='tratamiento',
        #     name='paciente',
        #     field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pacientes'),
        # ),
        # migrations.AlterField(
        #     model_name='atencion',
        #     name='descripcion',
        #     field=models.CharField(blank=True, max_length=300),
        # ),
    ]
