# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20180206_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_r',
            name='asistencia',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Asistencia'),
        ),
        migrations.AddField(
            model_name='log_r',
            name='fecha_ini',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log_r',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log_r',
            name='origen',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Origen'),
        ),
        migrations.AddField(
            model_name='log_r',
            name='tipo',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tipo'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='productos',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Productos'),
        ),
    ]
