# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20180117_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='tratamiento',
        ),
    ]
