# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
