# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_asiatencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asiatencia',
            new_name='Asistencia',
        ),
    ]
