# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_consulta_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='medicos',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Asiatencia',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Asistencia'),
        ),
    ]
