# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20180208_1342'),
    ]

    operations = [
       
    ]
