# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0057_consulta_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='domicilio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='email',
            field=models.CharField(max_length=300),
        ),
    ]
