# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20180124_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='celular',
            field=models.CharField(blank=True, max_length=300, verbose_name='Celular'),
        ),
    ]
