# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20180208_1433'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='log_pc',
        #     name='celular',
        #     field=models.CharField(blank=True, max_length=300),
        # ),
        # migrations.AddField(
        #     model_name='log_pc',
        #     name='dni',
        #     field=models.CharField(blank=True, max_length=300),
        # ),
        # migrations.AddField(
        #     model_name='log_pc',
        #     name='domicilio',
        #     field=models.CharField(blank=True, max_length=300, null=True),
        # ),
        # migrations.AddField(
        #     model_name='log_pc',
        #     name='email',
        #     field=models.CharField(blank=True, max_length=300, null=True),
        # ),
        # migrations.AddField(
        #     model_name='log_pc',
        #     name='estados',
        #     field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pestados'),
        # ),
        # migrations.AddField(
        #     model_name='log_pc',
        #     name='fecha_ini',
        #     field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        # ),
        # migrations.AddField(
        #     model_name='log_pc',
        #     name='nacimiento',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='pagos',
        #     name='productos',
        #     field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Productos'),
        # ),
    ]
