# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20180124_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='endhora',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='starthora',
        ),
        migrations.AddField(
            model_name='atencion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pacientes'),
        ),
    ]
