# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20180124_1446'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='tratamiento',
        #     name='medico',
        #     field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Medicos'),
        # ),
        # migrations.AddField(
        #     model_name='tratamiento',
        #     name='paciente',
        #     field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pacientes'),
        # ),
    ]
