# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20180125_1110'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='tiposventa',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('nombre', models.CharField(blank=True, max_length=300, null=True)),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='tratamiento',
        #     name='medico',
        #     field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Medicos'),
        # ),
        # migrations.AddField(
        #     model_name='tratamiento',
        #     name='paciente',
        #     field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pacientes'),
        # ),
    ]
